import type { EnglishForms } from './engine';

/**
 * English for each verb, keyed by the Egyptian file's slug so the dialects
 * line up. Three Egyptian glosses are wrong (احترم "to behave", جرى "to
 * happen", استنى "to stay"); the new dialects use the real meanings.
 */
const E = (base: string, past: string, present: string, presentThird: string): EnglishForms => ({
	base,
	past,
	present,
	presentThird
});

export const ENGLISH: Record<string, EnglishForms> = {
	wafi: E('to accept', 'accepted', 'accept', 'accepts'),
	'rah-ma3a': E('to accompany', 'accompanied', 'accompany', 'accompanies'),
	'mi-i-ma3a': E('to walk with', 'walked with', 'walk with', 'walks with'),
	abba: E('to adjust', 'adjusted', 'adjust', 'adjusts'),
	i3taraf: E('to admit', 'admitted', 'admit', 'admits'),
	'assar-3ala': E('to affect', 'affected', 'affect', 'affects'),
	samah: E('to allow', 'allowed', 'allow', 'allows'),
	'i3tazar-3an': E('to apologize for', 'apologized for', 'apologize for', 'apologizes for'),
	ahar: E('to appear', 'appeared', 'appear', 'appears'),
	qaddar: E('to appreciate', 'appreciated', 'appreciate', 'appreciates'),
	'ri-i-bi': E('to approve of', 'approved of', 'approve of', 'approves of'),
	'sa-al': E('to ask', 'asked', 'ask', 'asks'),
	'ha-ar': E('to attend', 'attended', 'attend', 'attends'),
	kan: E('to be', 'was', 'be', 'is'),
	ihtaram: E('to respect', 'respected', 'respect', 'respects'),
	rahin: E('to bet', 'bet', 'bet', 'bets'),
	'lam-3ala': E('to blame', 'blamed', 'blame', 'blames'),
	kasar: E('to break', 'broke', 'break', 'breaks'),
	hara: E('to burn', 'burned', 'burn', 'burns'),
	ihtamm: E('to care about', 'cared about', 'care about', 'cares about'),
	ghayyar: E('to change', 'changed', 'change', 'changes'),
	ixtar: E('to choose', 'chose', 'choose', 'chooses'),
	gih: E('to come', 'came', 'come', 'comes'),
	qarin: E('to compare', 'compared', 'compare', 'compares'),
	'itta-al-bi': E('to contact', 'contacted', 'contact', 'contacts'),
	kammil: E('to continue', 'continued', 'continue', 'continues'),
	rafa: E('to refuse', 'refused', 'refuse', 'refuses'),
	alab: E('to ask for', 'asked for', 'ask for', 'asks for'),
	nakar: E('to deny', 'denied', 'deny', 'denies'),
	'wa-af': E('to describe', 'described', 'describe', 'describes'),
	ammim: E('to design', 'designed', 'design', 'designs'),
	ixtalaf: E('to differ', 'differed', 'differ', 'differs'),
	ixtafa: E('to disappear', 'disappeared', 'disappear', 'disappears'),
	'wa-a3': E('to drop', 'dropped', 'drop', 'drops'),
	'3abbar-3an': E('to express', 'expressed', 'express', 'expresses'),
	'wi-i3': E('to fall', 'fell', 'fall', 'falls'),
	'la-a-la-a': E('to find', 'found', 'find', 'finds'),
	allah: E('to fix', 'fixed', 'fix', 'fixes'),
	afa: E('to float', 'floated', 'float', 'floats'),
	idda: E('to give', 'gave', 'give', 'gives'),
	rah: E('to go', 'went', 'go', 'goes'),
	gara: E('to run', 'ran', 'run', 'runs'),
	'ha-al': E('to happen', 'happened', 'happen', 'happens'),
	'kan-3andu': E('to have', 'had', 'have', 'has'),
	sa3id: E('to help', 'helped', 'help', 'helps'),
	arab: E('to hit', 'hit', 'hit', 'hits'),
	xaba: E('to bump into', 'bumped into', 'bump into', 'bumps into'),
	nawa: E('to intend', 'intended', 'intend', 'intends'),
	na: E('to jump', 'jumped', 'jump', 'jumps'),
	sab: E('to leave', 'left', 'leave', 'leaves'),
	kidib: E('to lie', 'lied', 'lie', 'lies'),
	'3a': E('to live', 'lived', 'live', 'lives'),
	'ba-li': E('to look at', 'looked at', 'look at', 'looks at'),
	xisir: E('to lose', 'lost', 'lose', 'loses'),
	'a-ad': E('to mean', 'meant', 'mean', 'means'),
	itharrak: E('to move', 'moved', 'move', 'moves'),
	harrak: E('to move (something)', 'moved', 'move', 'moves'),
	fatah: E('to open', 'opened', 'open', 'opens'),
	gahhiz: E('to prepare', 'prepared', 'prepare', 'prepares'),
	mana3: E('to forbid', 'forbade', 'forbid', 'forbids'),
	'3aqib': E('to punish', 'punished', 'punish', 'punishes'),
	warra: E('to show', 'showed', 'show', 'shows'),
	ghiri: E('to sink', 'sank', 'sink', 'sinks'),
	istanna: E('to wait', 'waited', 'wait', 'waits'),
	a3ad: E('to stay', 'stayed', 'stay', 'stays'),
	nigih: E('to succeed', 'succeeded', 'succeed', 'succeeds'),
	'a-xad': E('to take', 'took', 'take', 'takes'),
	mazza: E('to tear', 'tore', 'tear', 'tears'),
	akar: E('to thank', 'thanked', 'thank', 'thanks'),
	raba: E('to tie', 'tied', 'tie', 'ties'),
	lamas: E('to touch', 'touched', 'touch', 'touches'),
	ista3mil: E('to use', 'used', 'use', 'uses')
};
