<section class="p-4 text-text-300">
  <p>
    This keyboard is a tool that helps english speakers write in Arabic without having a dedicated arabic keyboard installed on their computer
  </p>
  <p>The keyboard is fully featured and contains support for all letters, numbers, special characters, diacritical marks, and text to speech.</p>
  <p>If you are not comfortable with the arabic alphabet yet please head over to <a href="/alphabet" class="underline !text-text-300">The alphabet learning section</a></p>
  <div class="tables">
    <div class="column">
      <div class="table_wrapper">
        <h4>Letters</h4>
        <details>
          <summary>More Info</summary>
          <p>
            Most letters in the arabic alphabet have a corresponding letter in english, for example <strong>ا</strong> roughly corresponds to the letter <strong>a</strong> in english.
          </p>
          <p>
            Arabic has emphatic letters. <strong>ص</strong> and
            <strong>ض</strong> are emphatic versions of
            <strong>س</strong> and <strong>د</strong> respectively. The emphatic letters are represented by capital letters in english, <strong>S</strong> and
            <strong>D</strong> respectively.
          </p>
          <p>
            There are some letters that have no corresponding letter in english such as <strong>ش</strong> and <strong>ث</strong>. These letters can be generated by typing the closest corresponding english letter followed by an apostrophe
            <strong>'</strong>. For example <strong>s'</strong> and
            <strong>t'</strong> respectively.
          </p>
        </details>
        <table>
          <thead>
            <tr>
              <th>English</th>
              <th>Arabic</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>a</td>
              <td>ا</td>
            </tr>
            <tr>
              <td>b</td>
              <td>ب</td>
            </tr>
            <tr>
              <td>t</td>
              <td>ت</td>
            </tr>
            <tr>
              <td>t + '</td>
              <td>ث</td>
            </tr>
            <tr>
              <td>j</td>
              <td>ج</td>
            </tr>
            <tr>
              <td>H</td>
              <td>ح</td>
            </tr>
            <tr>
              <td>x</td>
              <td>خ</td>
            </tr>
            <tr>
              <td>d</td>
              <td>د</td>
            </tr>
            <tr>
              <td>d + '</td>
              <td>ذ</td>
            </tr>
            <tr>
              <td>r</td>
              <td>ر</td>
            </tr>
            <tr>
              <td>z</td>
              <td>ز</td>
            </tr>
            <tr>
              <td>s</td>
              <td>س</td>
            </tr>
            <tr>
              <td>s + '</td>
              <td>ش</td>
            </tr>
            <tr>
              <td>S</td>
              <td>ص</td>
            </tr>
            <tr>
              <td>D</td>
              <td>ض</td>
            </tr>
            <tr>
              <td>T</td>
              <td>ط</td>
            </tr>
            <tr>
              <td>Z</td>
              <td>ظ</td>
            </tr>
            <tr>
              <td>g</td>
              <td>ع</td>
            </tr>
            <tr>
              <td>g + '</td>
              <td>غ</td>
            </tr>
            <tr>
              <td>f</td>
              <td>ف</td>
            </tr>
            <tr>
              <td>q</td>
              <td>ق</td>
            </tr>
            <tr>
              <td>k</td>
              <td>ك</td>
            </tr>
            <tr>
              <td>l</td>
              <td>ل</td>
            </tr>
            <tr>
              <td>m</td>
              <td>م</td>
            </tr>
            <tr>
              <td>n</td>
              <td>ن</td>
            </tr>
            <tr>
              <td>h</td>
              <td>ه</td>
            </tr>
            <tr>
              <td>w</td>
              <td>و</td>
            </tr>
            <tr>
              <td>y</td>
              <td>ي</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="column">
      <div class="table_wrapper">
        <h4>Special Characters</h4>
        <details>
          <summary>More info</summary>
          <p>
            <strong>Hamza (ء‎)</strong> is a letter in the Arabic alphabet, which represents the glottal stop
          </p>
          <p>
            To achieve this character, type <strong>-</strong> in english, and to achieve the <strong>hamza below alif (إ)</strong> type
            <strong>a--</strong> in english.
          </p>
        </details>
        <table>
          <thead>
            <tr>
              <th>English</th>
              <th>Arabic</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>-</td>
              <td>ء</td>
            </tr>
            <tr>
              <td>a--</td>
              <td>إ</td>
            </tr>
            <tr>
              <td>A--</td>
              <td>أ</td>
            </tr>
            <tr>
              <td>A</td>
              <td>آ</td>
            </tr>
            <tr>
              <td>u--</td>
              <td>ؤ</td>
            </tr>
            <tr>
              <td>y--</td>
              <td>ئ</td>
            </tr>
            <tr>
              <td>Y</td>
              <td>ى</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table_wrapper">
        <h4>Diacritics</h4>
        <details>
          <summary>More Info</summary>
          <p>
            In Arabic, diacritic marks are symbols used to indicate the pronunciation of letters and to clarify the correct reading of words. These marks are called "harakat" (حركات) or "tashkil" (تشكيل). Arabic script is an abjad, which means it primarily represents
            consonants, and diacritic marks help convey the appropriate vowel sounds.
          </p>
          <ul>
            <li>بَ - Ba with Fatha - Pronounced "ba" as in "bat."</li>
            <li>بُ - Ba with Damma - Pronounced "bu" as in "but."</li>
            <li>بِ - Ba with Kasra - Pronounced "bi" as in "bit."</li>
            <li>
              بّ - Ba with Shadda - Indicates a doubled or emphasized "b" sound.
            </li>
            <li>
              بْ - Ba with Sukun - Indicates that the letter is a consonant with no associated vowel sound.
            </li>
            <li>بٌ - Ba with Dammatan - Indicates the sound "bun."</li>
            <li>بٍ - Ba with Kasratan - Indicates the sound "bin."</li>
            <li>بً - Ba with Fatahan - Indicates the sound "ban."</li>
          </ul>
        </details>
        <table>
          <thead>
            <tr>
              <th>English</th>
              <th>Arabic</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>a + =</td>
              <td class="ar_diacritic">َ</td>
            </tr>
            <tr>
              <td>an + =</td>
              <td class="ar_diacritic">ً</td>
            </tr>
            <tr>
              <td>u + =</td>
              <td class="ar_diacritic">ُ</td>
            </tr>
            <tr>
              <td>un + =</td>
              <td class="ar_diacritic">ٌ</td>
            </tr>
            <tr>
              <td>i + =</td>
              <td class="ar_diacritic">ِ</td>
            </tr>
            <tr>
              <td>in + =</td>
              <td class="ar_diacritic">ٍ</td>
            </tr>
            <tr>
              <td>s + =</td>
              <td class="ar_diacritic">ّ</td>
            </tr>
            <tr>
              <td>h + =</td>
              <td class="ar_diacritic">ْ</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table_wrapper">
        <h4>Numbers</h4>
        <table>
          <thead>
            <tr>
              <th>English</th>
              <th>Arabic</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>١</td>
            </tr>
            <tr>
              <td>2</td>
              <td>٢</td>
            </tr>
            <tr>
              <td>3</td>
              <td>٣</td>
            </tr>
            <tr>
              <td>4</td>
              <td>٤</td>
            </tr>
            <tr>
              <td>5</td>
              <td>٥</td>
            </tr>
            <tr>
              <td>6</td>
              <td>٦</td>
            </tr>
            <tr>
              <td>7</td>
              <td>٧</td>
            </tr>
            <tr>
              <td>8</td>
              <td>٨</td>
            </tr>
            <tr>
              <td>9</td>
              <td>٩</td>
            </tr>
            <tr>
              <td>0</td>
              <td>٠</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

<style>
  @-ms-viewport {
  width: device-width;
}

body {
  background-color: #F2F6F7;
  font-family: Helvetica, Arial, sans-serif;
  overflow-x: hidden;
  color: #2E282A;
}

a {
  color: blue;
}

a:visited {
  color: blue;
}

span {
  font-size: 25px;
  margin-right: 6px;
  color: blue;
}

main {
  margin: auto;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  padding: 10px;
  align-items: center;
  width: 100%;
  background-color: #F2F6F7;
  justify-content: center;
}

header {
  width: 100%;
  margin-top: 30px;
}

.nav {
  display: flex;
  flex-direction: row;
  gap: 6px;
}

ul {
  margin-bottom: 8px;
}

arabic-keyboard {
  display: block;
  margin-top: 12px;
  --max-keyboard-width: 100%
}

section {
  margin-top: 36px;
  text-align: left;
  width: 100%;
}

p {
  font-size: 18px;
  line-height: 1.5;
  margin: 4px 0;
}

h1 {
  color: #2E282A;
  font-weight: 900;
  font-size: 36px;
}

h3 {
  color: #2E282A;
  font-weight: 900;
  font-size: 24px;
}

span {
  display: inline-block;
}

.tables {
  display: flex;
  flex-direction: column;
  gap: 24px;
  margin-top: 24px;
  width: 100%;
}


/* Mobile */

@media only screen and (min-width: 420px) {
  .tables {
    flex-direction: row;
  }
}


/* Desktop */

@media only screen and (min-width: 900px) {
  header {
    width: 100%;
  }
  .tables {
    flex-direction: row;
  }
}

.column {
  display: flex;
  flex-direction: column;
  gap: 24px;
  flex: 1;
}

.table_wrapper {
  width: 100%;
}

summary {
  cursor: pointer;
}

details>p {
  font-size: 16px;
  margin: 6px 0;
  line-height: 1.25;
}

table {
  margin-top: 4px;
  width: 100%;
  font-family: arial, sans-serif;
  border-collapse: collapse;
}

h4 {
  font-size: 20px;
  font-weight: 900;
  text-align: left;
  margin-bottom: 12px;
}

strong {
  font-weight: 900;
  font-style: italic;
}

thead {
  background-color: var(--tile5);
  font-size: 18px;
}

td,
th {
  border: 1px solid var(--tile6);
  text-align: left;
  padding: 8px;
}

td {
  font-size: 20px;
}

.ar_diacritic {
  font-size: 40px;
}

li {
  margin: 4px 0;
}

tr:nth-of-type(even) td {
  background-color: var(--tile4);
}

h4 {
  margin: 16px 0;
}
</style>